# version: "3.8"
# services:
#   mongo:
#     image: mongo:6
#     restart: always
#     container_name: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

#   backend:
#     build: ./backend
#     restart: always
#     container_name: backend
#     ports:
#       - "5000:5000"
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/yourdbname
#       - NODE_ENV=production
#     depends_on:
#       - mongo

#   frontend:
#     build: ./frontend
#     restart: always
#     container_name: frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

# volumes:
#   mongo-data: 
version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: school_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=school_management
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: ghcr.io/sanjdcool/mern-school-management-system_mine1-backend:latest
    container_name: school_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/school_management
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: ghcr.io/sanjdcool/mern-school-management-system_mine1-frontend:latest
    container_name: school_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge